docs/account.rst

Check order status

---

binance/depthcache.py

Added the ability to make the callback for DepthCacheManager 'None' if you don't want or need a callback.

Added 'None' callback for DepthCacheManager

---

PYPIREADME.rst
README.rst
binance/depthcache.py
docs/changelog.rst
setup.py

Open the depth update socket and buffer its messages prior to taking the initial depth snapshot.

Buffer depth update messages prior to snapshot

---

binance/client.py

This would fix the error as described in issue #61

Update for client.py

---

README.rst

Fix typo in demo code.

---

binance/helpers.py

Add 1M to interval_to_milliseconds, simplify logic, add doctest.

feat(helpers): Add 1M to interval_to_milliseconds

---

README.rst
binance/websockets.py
docs/account.rst

According to Docs every 30 minutes the User Websocket Stream can be
keeped alive using `PUT /api/v1/userDataStream`, keeping the same
`listenKey`. This should resolve #119.

Changed the Keep Alive strategy for User Websocket Stream.

---

binance/websockets.py

Listen for the `user_listen_key` change and start a new socket
with the key obtained without request another one.
Prevents `_start_user_timer` to starting twice when the user key
changes.
Added a new method `_start_user_socket` that accepts a user key.

Update User Websocket keepalive strategy.

---

README.rst

Client.KLINE_INTERVAL_1WEEK was missing client.

forgot var in sample

---

binance/websockets.py

allow custom user_timeout

---

binance/websockets.py

Fixed User Data Stream Binance API link

Fixed link in docs

---

binance/client.py

Add param to function call in order to developer can change limit parameter.

Add limit param to control function behavior

---

tests/test_historical_klines.py

Would like to slowly improve test coverage and quality for this project.

Added historical kline tests

---

binance/client.py
binance/websockets.py

Usage is same as start_user_socket(), but it listens to userData on user's margin account.

start_margin_socket() to listen for userData on margin account

---

Endpoints.md

Hey @kimchirichie,
I've checked everything twice to fix typos etc. If you find something not correct, please tell me. It would be great, if you add also a link from main readme. 
Mo

Add Endpoints.md, closes #610

---

binance/client.py

Hi,
link to the endpoint: https://binance-docs.github.io/apidocs/spot/en/#get-fixed-and-activity-project-list-user_data
Thanks!

Add get_fixed_activity_project_list method

---

binance/client.py

added 2 new endpoints:
1. Query Sub-account Futures Asset Transfer History(For Master Account)
2. Sub-account Futures Asset Transfer(For Master Account)
From Binance api Change Log 2020-09-03

Sub account endpoints - futures transfer & history

---

binance/depthcache.py

I have multiple DepthCacheManager's going and would like to know what symbol each one is for

Added get symbol method

---

binance/client.py

Fixes: https://github.com/sammchardy/python-binance/issues/556
Not sure about `DELETE userDataStream`.
I left that at `v1`, because it is not mentioned in the [Binance changelog](https://binance-docs.github.io/apidocs/spot/en/#change-log) for **2019-11-13**.

Migrate some deprecated v1 endpoints to v3.

---

binance/client.py

seems like the endpoint was changed.
solves issues #514 and #525

Updates the get_product endpoint

---

binance/depthcache.py
binance/websockets.py

10x faster updates on order books, as described [here](https://www.binance.com/en/support/articles/360032916632)

[New feature] Faster order book updates

---

binance/websockets.py

Hi,
Thanks for the great library.
Just a small edit to enable use of ujson over stdlib json.
Thanks again.

Use ujson as deserializer over stdlib json, if possible

---

binance/websockets.py

I noticed there wasn't a way to get the agg trades for the futures stream so added in the function to get this data.

Add aggtrade for futures stream

---

binance/depthcache.py

fixed depth cache sync in _init_cache

---

binance/client.py

It's a get request instead of a post request.

Fix margin api http method

---

binance/client.py

- calculate timestamp offset between binance server and local
- apply timestamp offset

fix: resolve timestamp mismatching issue

---

binance/client.py
docs/general.rst

Also fix https://github.com/sammchardy/python-binance/issues/730

Some docs fix. Cosmetic

---

docs/overview.rst

Fix broken Markdown link

---

.gitignore
Endpoints.md
PYPIREADME.rst
README.rst
binance/client.py
docs/sub_accounts.rst
docs/withdraw.rst

Migrate from WAPI to SAPI.
@sammchardy 
@kimchirichie 
Fix #768
Fix #780

Migrate from wapi to sapi

---

setup.py

I also recommend having [this](https://packaging.python.org/guides/making-a-pypi-friendly-readme/#validating-restructuredtext-markup) a read for validating reStructuredText markup to PyPi just in case.

Added long description

---

README.rst

`while _ in range(5)` throw errors. Change it into `for _ in range(5)`

Fix syntax in streams example

---

binance/streams.py

Changed an annoying print with logging.debug.
Fixes #839

fix(Streams): Changed print with logging.debug

---

binance/streams.py

multiplex_socket and book_ticker_socket typos
closes #843

ThreadedWebsocketManager fix

---

binance/streams.py

streams: futures_multiplex replace socket_name fix

---

Endpoints.md
binance/client.py

related issue: #883 raise BinanceAPIException when call futures_open_interest

fix: Modify futures_open_interest func to correct api url

---

binance/client.py

add get_ticker() to retrieve one ticker
update get_all_tickers()

fix wrong return type for get_all_tickers

---

binance/streams.py

adding symbol miniTicker 
https://github.com/binance/binance-spot-api-docs/blob/master/web-socket-streams.md#individual-symbol-mini-ticker-stream

add Symbol miniTicker stream to Binance Socket Manager

---

binance/client.py

I tried to place batch order by function [futures_coin_place_batch_order], but I finally found this function doesn't exist.
So I add it to client.py for simple use for beginner.

Update client.py 

---

docs/overview.rst

fix https://github.com/sammchardy/python-binance/issues/920

Fix typo in Synchronous rate limit example

---

binance/client.py

added api permissions endpoint to client.py for both Client and asyncClient

added api permissions endpoint

---

docs/websockets.rst

fixed some grammar in the websockets documentation.

Fix grammar in websockets.rst

---

binance/client.py

hi, I just partially implemented some fiat endpoints in sync client. Pls merge if it's ok.

#1005, methods for getting fiat deposit/withdraw history in sync client

---

binance/depthcache.py
binance/streams.py
setup.py

Also making version search more window$ friendly

Adding futures depth cache manager

---

Endpoints.md
binance/client.py

Hi,
Following endpoints(methods) have been added:
https://binance-docs.github.io/apidocs/spot/en/#get-all-margin-assets-market_data
https://binance-docs.github.io/apidocs/spot/en/#get-all-cross-margin-pairs-market_data
https://binance-docs.github.io/apidocs/spot/en/#get-interest-history-user_data
https://binance-docs.github.io/apidocs/spot/en/#get-force-liquidation-record-user_data

Add some endpoints

---

binance/depthcache.py
binance/streams.py

Dedicated logger: use logger instead of logging

---

binance/streams.py

* Fix variable name mess
* Fix blocking dead loop in some cases

Fix streams.py read loop

---

binance/client.py

https://binance-docs.github.io/apidocs/spot/en/#kline-candlestick-data

klines limit max value has long been raised to 1000

---

binance/streams.py

Remove loop parameter as it is no longer supported by asyncio
Fixes Issue #1058

fix Issue #1058

---

binance/streams.py

Hey! Love this project and been using it lots lately. Noticed there wasn't support for depth sockets for futures contracts so went ahead and ahead some here.

Added depth sockets for futures and coin-m futures

---

binance/streams.py

It appears that start_futures_user_socket was missing, so I just added it.

Added start_futures_user_socket to streams.py

---

tests/test_historical_klines.py

Fix the historical kline tests by setting all limits to 1000.

Fix tests by increasing limits to 1000

---

docs/overview.rst

1200 weights, not 1200 requests

fixed inaccurate information about API limit

---

binance/streams.py

Run reconnect once may encounter network error, and then `await self._wait_for_reconnect()` would cause an infinite loop

fix reconnect failure

---

binance/client.py
test-requirements.txt

Update client.py (added staking enpoints)

---

binance/client.py

add Pay Trade History (USER_DATA)

added Pay C2C Trade History in client.py

---

binance/client.py

This is a new api available in binance.us

Adding get staking balance

---

binance/client.py

Hello,
The request has to be sent as a post request not as a get request : https://binance-docs.github.io/apidocs/spot/en/#user-asset-user_data

get_binance_balance changing method get to post

---

binance/client.py

funding_wallet and get_user_asset methods fix

---

binance/client.py

Added functions "isolated_margin_fee_data" and "isolated_margin_tier_data" with documentation

Added isolated margin fee data and isolated margin tier data

---

binance/client.py

binance.us uses a different endpoint for trade fee

get_trade_fee support for binance.us

---

binance/client.py

The name of the function has been bugging me for sometime, so I added "get_" to it, and fixed the "code block" in the documentation.

A few quality of life fixes for the previous pull

---

binance/streams.py

Binance has added coin futures.
Add coin_futures_user_socket for this library.

Add coin_futures_user_socket

---

binance/client.py

- relates to https://github.com/sammchardy/python-binance/issues/1396

feat(binance): add eddsa signing

---

binance/client.py

Adding new binance API function https://binance-docs.github.io/apidocs/spot/en/#rolling-window-price-change-statistics

Add new binance endpoint rolling-window-price-change-statistics

---

binance/client.py
tests/test_futures.py
tests/test_ids.py

- relates to https://github.com/sammchardy/python-binance/issues/1420

feat(client): positionRisk to v3 and allow version override in params

---

binance/client.py
binance/streams.py

https://github.com/sammchardy/python-binance/issues/960

Fix # 960: AttributeError("'Connect' object has no attribute 'protocol'")

---

binance/client.py
tests/test_ids.py

also my IDE make some minor edits to the spacing

add x- to broker prefix

---

tests/conftest.py
tests/test_client.py
tests/test_get_order_book.py
tests/test_ping.py

- Adds test client fixture
- Adds tests for `get_order_book`

feat: add testing client and order book

---

binance/streams.py
binance/threaded_stream.py
tests/test_socket_manager.py
tests/test_threaded_socket_manager.py

fix: threadApiManager

---

README.rst
binance/__init__.py
docs/changelog.rst

- relates to https://github.com/sammchardy/python-binance/issues/1483

chore: bump to v1.0.24

---

docs/conf.py
docs/requirements.txt

feat: Add copy button in docs

---

binance/async_client.py
binance/base_client.py
binance/client.py

- fixes https://github.com/sammchardy/python-binance/issues/1396

fix(client): EDDSA signing with POST methods

---

binance/async_client.py
binance/client.py

Adds docs for WS - API endoints

chore: add missing docs for ws endpoints
