sammchardy/python-binance

README.rst
Capitalization of exception class name was wrong.
=> Fix typo in quick start code

PYPIREADME.rst, README.rst
The example throws an error when being run,
```
APIError(code=403): Access denied
Traceback (most recent call last):
File "test.py", line 55, in <module>
bm.start_aggtrade_socket(symbol='BNBBTC')
TypeError: start_aggtrade_socket() takes exactly 3 arguments (2 given)
```
And because the first argument is being called with a keyword, all subsequent arguments also require a keyword.
=> Using keyworded callback

.gitignore, PYPIREADME.rst, README.rst, docs/changelog.rst, setup.py
Changes to `.gitignore` and `setup.py` for successful build and install on Mac 10.13.2 (17C88) using Homebrew 1.4.3.
=> Minor fixes for building on Mac OS X using Brew

PYPIREADME.rst, README.rst, binance/client.py, docs/changelog.rst, setup.py
Hi Sam,
It was [reported](https://github.com/sammchardy/python-binance/issues/183) that historical klines will crash when the number of data points returned matches the limit exactly.
Kline loop was only exiting when the data return was < limit so this makes sense.
It caused the loop to run once more, retrieve an empty kline dataset, then fall over when trying to access the [-1] index of the empty dataset.
I added a test that will also break the loop if an empty kline dataset is returned (after the symbol_existed).
Pretty sure this would have taken you about as long to write yourself than handle this PR but I'm new to github and fancied the chance to try this out.
Thanks for the library, it helped me out a lot getting off the ground trading,
Michael
=> Patch historical klines to handle case where results exactly equal limit

binance/client.py
I imagine it would be better to remove all limits, defaults, etc. from documentation here and refer the user to the official Binance API docs to avoid skew as the API changes underneath.
=> Fixed the max on the get_order_book limit param.

binance/exceptions.py
`LISTENKEY_NOT_EXIST` was introduced by Sam McHardy in commit 3508a647. The mechanism which it was used in has since been removed, leaving `LISTENKEY_NOT_EXIST` unused.
=> Remove unused LISTENKEY_NOT_EXIST

binance/client.py
With the previous implementation, using start_str='30 minutes ago UTC' gives error (Illegal characters found in parameter 'endTime'; legal range is '^[0-9]{1,20}$') because the time was / by 2 and then not casted to int resulting in a float value. When this was fixed I noticed that the end time interval does matter, as the Binance API is requesting one hour intervals, so half day does not work anymore (binance.exceptions.BinanceAPIException: APIError(code=-1127): More than 1 hours between startTime and endTime). 
Error mentioned in #215
=> Fix time interval bug aggregate_trades_iter

binance/depthcache.py
This works for me and seems like a pretty big improvement for people running multiple depth cache managers. The only problem with it is that it changes the behaviour of `dcm.close()`.
I also added the sleep during the close re: #276.
=> allow DepthCacheManager to share a SocketManager

binance/client.py
Fixes #341.
When starting from startStr, if the first hour doesn't contain any trades, it will now not crash, but move forward hour by hour until it at least one trade is found or present moment is reached.
=> aggregate_trade_iter(): fixed empty resulting set problem

binance/websockets_async.py
Omitted 'prefix' parameter generates wrong connection url for multiplex socket
=> Fix start_multiplex_socket

binance/client.py
- In Client._get_earliest_valid_timestamp(), endTime is set to None, which results in a server-side error.
=> Added support for stripping None-valued parameters

binance/websockets.py
Book ticker sockets added among websocket API.
Following streams are part of the PR:
https://github.com/binance-exchange/binance-official-api-docs/blob/master/web-socket-streams.md#individual-symbol-book-ticker-streams
https://github.com/binance-exchange/binance-official-api-docs/blob/master/web-socket-streams.md#all-book-tickers-stream
=> Book ticker sockets added

binance/client.py
Allows support for both binance.us and binance.com through changing URL variables in client initialization using the tld parameter.
=> Allows support for binance.us and binance.com

Endpoints.md, binance/client.py, binance/websockets.py, docs/websockets.rst
Continuing the implementation of Isolated Margin accounts (closed PR #622 ), this now adds the websockets under BinanceSocketManager.  
I need this for my project so have written neatly and am posting a PR back to the community.
**Isolated Margin Socket**
* `bm.start_isolated_margin_socket(symbol, callback)` now opens a websocket on the Isolated Margin account for `symbol`.
* Uses the same API pattern as the spot and cross-margin endpoints, except that we also have to pass in the `symbol`.  
* Docs updated for the new WS endpoints.  I also added the cross-margin WS socket to the docs as it seemed to be missing.
Technical implementation note for maintainers ... 
* The `bm._listen_keys` `bm._timers` and `bm._account_callback` dictionaries need to expand with potentially many isolated margin …
=> Added websockets functionality for isolated margin accounts

README.rst, binance/client.py, docs/account.rst, docs/margin.rst
- Binance spot document moved to https://github.com/binance/binance-spot-api-docs
- Margin or other modules is managed by https://binance-docs.github.io/apidocs/spot/en/#change-log only.
=> update the document links as Binance spot repo relocated.

Endpoints.md
There is a small typo in Endpoints.md.
Should read `mandatory` rather than `mendatory`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
=> docs: fix simple typo, mendatory -> mandatory

binance/client.py
I noticed that there are some endpoints in [binance future api doc](https://binance-docs.github.io/apidocs/futures/en/#change-log) not implemented in this python sdk yet. 
This PR add one endpoint [futures_change_position_mode](https://binance-docs.github.io/apidocs/futures/en/#change-position-mode-trade) to binance/client.py
=> add futures_change_position_mode

binance/client.py
For now the endpoint is broken (having a whitespace in the end) and results in:
```
Traceback (most recent call last):
File "/home/vilen/repos/crypto/venv/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3343, in run_code
exec(code_obj, self.user_global_ns, self.user_ns)
File "<ipython-input-18-e9f064622c02>", line 1, in <module>
client.get_lending_product_list()
File "/home/vilen/repos/crypto/venv/lib/python3.7/site-packages/binance/client.py", line 3185, in get_lending_product_list
return self._request_margin_api('get', 'lending/daily/product/list ', signed=True, data=params)
File "/home/vilen/repos/crypto/venv/lib/python3.7/site-packages/binance/client.py", line 212, in _request_margin_api
return self._request(method, uri, signed, **kwargs)
File …
```
=> Fixes for get_lending_product_list REST endpoint

binance/client.py, binance/helpers.py, docs/helpers.rst, examples/save_historical_data.py, tests/test_historical_klines.py
The official binance API supports 1M interval for obtaining historical klines data. 
(ex. `https://api.binance.com/api/v1/klines?interval=1M&symbol=BNBBTC`)
So I added it.
=> Add 1 Month Interval (1M) for Historical Klines

binance/client.py
To overcome the message "unclosed client connection", create a function with let the user manually disconnect the aiohttp session
=> Add function to manually disconnect the aiohttp connection

docs/changelog.rst, requirements.txt, setup.py
You added ujson (https://github.com/sammchardy/python-binance/pull/383) and its missing in the requirements!
=> adding ujson to reqirements.txt and setup.py

binance/client.py
I noticed that your library only implemented the "get" HTTP function on the transfer endpoint, which queries for transfer history.  I added the "post" version which allows you to transfer funds to/from your futures account from your spot account.
I noticed for margin trading, you explicitly made separate functions for each transfer direction: https://github.com/sammchardy/python-binance/blob/master/binance/client.py#L2500-L2558
But it seems the standard account stuff was more fleshed out in terms of documentation and function parameters.  The futures stuff seems to be left to the developer to read API docs, thus I did it that way.  I can implement separate to/from functions if you prefer.  Just let me know.
=> Added function to transfer funds from/to spot account and futures account

binance/websockets.py
I was experiencing the #597 bug
By logging the python-binance websocket connection I found an SSL error when using testnet.binance.vision:
`
2021-02-03 21:33:03-0300 [-] SSL error: wrong version number (in ssl3_get_record)
`
I digged around and found this:
https://forum.crossbar.io/t/ssl-error-wrong-version-number-in-ssl3-get-record/1832
For logging the websocket error add this to the websockets.py header:
```python
import sys
from twisted.python import log
log.startLogging(sys.stdout)
```
It is working for me.
=> fix: uses ssl.optionsForClientTLS for testnet.binance wss

binance/client.py
This is more explicit than just checking the first digit and would still throw an exception if the status code was 20 or 2000 (obviously invalid), for example.
=> Clean up error response detection

binance/client.py, docs/general.rst
In this PR I've added the support for the All Coins Information endpoint, and also updated the docs.
```
All Coins' Information (USER_DATA)
Get information of coins (available for deposit and withdraw) for user.
GET /sapi/v1/capital/config/getall (HMAC SHA256) 
```
See Binance docs for more informations about this endpoint :
https://binance-docs.github.io/apidocs/spot/en/#system-status-system
=> Add Get All Coins Information endpoint

tests/test_api_request.py, tests/test_historical_klines.py
I noticed that some tests were failing because the actual URLs didn't match the mock URLs.
I updated the mock URLs so that the tests now pass.
=> Mock URLs now match actual version

binance/client.py
Add methods to retrieve Open Interest Statistics for both USD-M Futures and COIN-M Futures.
Created dedicated "futures/data" URLs as in doc:
- https://binance-docs.github.io/apidocs/futures/en/#open-interest-statistics
- https://binance-docs.github.io/apidocs/delivery/en/#open-interest-statistics-market-data
=> add Open Interest Statistics

Endpoints.md, binance/client.py, docs/general.rst
In this PR I've added the support for the Daily Account Snapshot endpoint, and also updated the docs.
Daily Account Snapshot (USER_DATA)
GET /sapi/v1/accountSnapshot (HMAC SHA256) 
See Binance docs for more informations about this endpoint :
https://binance-docs.github.io/apidocs/spot/en/#daily-account-snapshot-user_data
=> Add Get Daily Account Snapshot endpoint

Endpoints.md, binance/client.py, docs/account.rst
In this PR I've added the support for the Account API Trading Status endpoint, and also updated the docs.
Account API Trading Status (USER_DATA)
GET /wapi/v3/apiTradingStatus.html
https://binance-docs.github.io/apidocs/spot/en/#account-api-trading-status-user_data
=> Add account API trading status endpoint.

Endpoints.md, binance/client.py, docs/account.rst
In this PR I've added the support for the `Disable Fast Withdraw Switch` and `Enable Fast Withdraw Switch` endpoints, and also updated the docs.
Disable Fast Withdraw Switch (USER_DATA)
POST /sapi/v1/account/disableFastWithdrawSwitch (HMAC SHA256)
https://binance-docs.github.io/apidocs/spot/en/#disable-fast-withdraw-switch-user_data
Enable Fast Withdraw Switch (USER_DATA)
POST /sapi/v1/account/enableFastWithdrawSwitch (HMAC SHA256) 
https://binance-docs.github.io/apidocs/spot/en/#enable-fast-withdraw-switch-user_data
=> Add Disable/Enable Fast Withdraw Switch endpoints.

binance/client.py
For USD-M Futures Continuous Contract Kline/Candlestick Data  (request  /fapi/v1/continuousKlines)
=> add USD-M futures continous klines

binance/client.py
Implements a `get_historical_klines` and `get_historical_klines_generator` for futures. 
It was also requested in https://github.com/sammchardy/python-binance/issues/434#issuecomment-596137685
=> get_historical_klines for futures

.gitignore, Endpoints.md, binance/client.py, binance/depthcache.py, binance/websockets.py, docs/depth_cache.rst
Implements support for Binance's new vanilla options product. Their API documentation can be found [here](https://binance-docs.github.io/apidocs/voptions/en/#general-info).
This PR adds all the current REST endpoints, websockets for vanilla options and an OptionsDepthCacheManager. It also adds vanilla options testnet support in both REST and websockets however I have been unable to fully verify the websocket implementation as there has been no activity on the testnet platform. It does make a successful connection however so probably would work.
=> Added Vanilla Options Support

binance/websockets.py
If the stream is open, ping it every `DEFAULT_USER_TIMEOUT`:
Keepalive a user data stream to prevent a time out. User data streams will close after 60 minutes. It's recommended to send a ping about every 30 minutes (Which is the `DEFAULT_USER_TIMEOUT`).
Fixes #712 
Fixes #440
=> fix: Keepalive a user data stream to prevent a time out

docs/overview.rst
1. Update Binance link to create API Key - old url was dead
2. Fix markdown broken link
=> Update Binance link to create API Key

binance/client.py
Due to change https://github.com/sammchardy/python-binance/commit/eb790b389ccb0956d9ec1410103125e6f6a7cccd, it was not possible for unsigned requests to make use of the `requests_params` kwarg.
This PR fixes this bug.
=> Allow requests_params to be set for unsigned requests

binance/client.py
Fix def_withdraw_history_id, "withdrawId" key does not exist in binance output
When calling get_withdraw_history_id, the following exception was being thrown:
line 2644, in get_withdraw_history_id
for entry in result['withdrawList']:
TypeError: list indices must be integers or slices, not str
It seems that there is no ["withdrawList"] in the result, existing, just removed it
=> Fix def withdraw_history_id, "withdrawId" key does not exist in binance output

Endpoints.md
Delete the warnings of `openInterest` in Endpoints.md doc file, because now the function is working fine.
Related pull requests: #884
=> docs: Remove warning of openInterest in Endpoint.md

binance/client.py
connection to binance should be closed when a client is deleted (garbage collected). If we do not close the connection a resource warning like the following will be thrown (esp. in unittest) :
```
ResourceWarning: unclosed <ssl.SSLSocket fd=21, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('192.168.6.6', 40258), raddr=('52.84.150.34', 443)>
```
=> closing connection when client is deleted

binance/client.py
asset is the legacy param name; now the API expects `coin` instead.
=> Fix asset->coin param migration in withdrawal api

binance/enums.py, binance/streams.py
An endpoint for futures klines has been added. 
- The endpoint subscribes to the binance futures klines. 
- It works with USD-M, COIN-M. 
- It works also for the contract types perpetual, current quarter and next quarter.
- Added an enum for contract types
=> #941 added futures klines stream

binance/streams.py
- 建立一个websocket，断开网络
- websocket不会抛出异常，同时不会尝试重联
- 修复异常导致的websocket断开后不回去重联的问题
=> hotfix: 修复websocket异常断开后不报异常不重联的bug

binance/streams.py
1. Updated the path for kline_futures_socket to get the contract_type.value.  Use prefix = 'ws/'
2. Updated start_kline_futures_socket not to pass the enum values but the enum themselves.
Tested with below codes:
```
import time
from datetime import datetime
from binance import ThreadedWebsocketManager, AsyncClient
from binance.enums import FuturesType, ContractType
def main():
twm = ThreadedWebsocketManager()
twm.start()
def handle_multiplex_socket_message(msg):
print(str(msg))
def handle_socket_message(msg):
print(str(msg))
twm.start_kline_socket(callback=handle_socket_message, symbol='XLMUSDT')
twm.start_multiplex_socket(callback=handle_multiplex_socket_message, streams=['galausdt@kline_1m'])
twm.start_futures_multiplex_socket(callback=handle_multiplex_socket_message, …
```
=> Fix start_kline_futures_socket issue #1040

binance/client.py
3 of the endpoints that are not yet implemented in the library include:
1. /futures/data/globalLongShortAccountRatio
2. /futures/data/topLongShortPositionRatio
3. /futures/data/takerlongshortRatio
I've added the 3 corresponding functions in the client.
I'm not yet very familiar with the package but I tried to run a small test on the futures_global_longshort_ratio and I got an error:
`binance.exceptions.BinanceAPIException: APIError(code=0): Invalid JSON error message from Binance: <!DOCTYPE html>
`
The code that generated that error was:
`client.futures_global_longshort_ratio(symbol='BNBUSDT')
`
Please help me fixing it so we can merge the code.
=> Long short ratio API implementation

binance/client.py
Added more documentation about the return values for the `Client.get_historical_klines` function. Further addresses #475.
=> Documentation for Client.get_historical_klines

binance/streams.py
While exiting, the reconnect function causes a hanging thread or unclean exit. Checking for the EXITING state seems to solve this issue.
=> Avoid keep-alive hanging while exiting

binance/depthcache.py, binance/streams.py
Instantiating a ThreadedDepthCacheManager frequently fails due to it having not had time to instantiate an AsyncClient before creating objects that depend on it having been created.
The demo code:
```
from binance import ThreadedDepthCacheManager
def main():
dcm = ThreadedDepthCacheManager()
dcm.start()
def handle_depth_cache(depth_cache):
print(f"symbol {depth_cache.symbol}")
print("top 5 bids")
print(depth_cache.get_bids()[:5])
print("top 5 asks")
print(depth_cache.get_asks()[:5])
print("last update time {}".format(depth_cache.update_time))
dcm_name = dcm.start_depth_cache(handle_depth_cache, symbol='BNBBTC')
dcm_name = dcm.start_depth_cache(handle_depth_cache, symbol='ETHBTC')
dcm.join()
if __name__ == "__main__":
main()
```
Results in the following stack trace because client is None: …
=> Fix bug in ThreadedDepthCacheManager where self._client==None

binance/client.py
`futures_change_multi_assets_mode` method's `params` variable is of type `set`, which will lead to a TypeError here:
```
----> 1 await client.futures_change_multi_assets_mode(multiAssetsMargin=True)
.../site-packages/binance/client.py in futures_change_multi_assets_mode(self, multiAssetsMargin)
8118             'true' if multiAssetsMargin else 'false'
8119         }
-> 8120         return await self._request_futures_api('post', 'multiAssetsMargin', True, data=params)
8121
8122     async def futures_get_multi_assets_mode(self):
.../site-packages/binance/client.py in _request_futures_api(self, method, path, signed, **kwargs)
7177         uri = self._create_futures_api_uri(path)
7178
-> 7179         return await self._request(method, uri, signed, True, **kwargs)
7180
7181     async def …
```
=> Fix multiAssetsMargin params

binance/client.py
Get Isolated Margin Transfer History not implemented in current client. 
Added function for this endpoint:
https://binance-docs.github.io/apidocs/spot/en/#get-isolated-margin-transfer-history-user_data
=> added function for query isolated margin transfer history

binance/client.py
According to the API docs, startTime is optional for the endpoint /api/v3/klines
https://binance-docs.github.io/apidocs/spot/en/#kline-candlestick-data
Updating the client method get_historical_klines() to follow the official documentation.
I manually tested the update and was able to send API calls without the start_str parameter
=> make startTime optional for get_historical_klines()

binance/helpers.py
original one returns wrong:
```
>>> round_step_size(2.6, 1)
3.0
```
not exactly "wrong" for numbers such as 0.001, it rounds as stated, but you might not have that extra 0.4 coins when creating orders. also it won't work with anything else than powers of 0.1:
```
>>> round_step_size(55.3, 0.2)
55.3
```
this one properly rounds to step size, even with floats such as 0.003:
```
>>> round_step_size(2.6, 1)
2.0
>>> round_step_size(2.6, 0.003)
2.598
```
decided to contribute this after a few hours of floating point nightmare
=> better round_step_size function

binance/streams.py
Though `asyncio.create_task` is run after timeout,
`self._keepalive_socket()` is run right after connect.
When the socket is unexpectedly canceled, this happens
never-awaited coroutine error.
```
/opt/homebrew-x86/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/events.py:73: RuntimeWarning: coroutine 'KeepAliveWebsocket._keepalive_socket' was never awaited
Coroutine created at (most recent call last)
File "/opt/homebrew-x86/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/runners.py", line 44, in run
return loop.run_until_complete(main)
File "/opt/homebrew-x86/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 629, in run_until_complete
self.run_forever() …
```
=> Prevent never awaited coroutine from KeepAliveWebsocket._keepalive_socket

binance/client.py
When end_ts is passed historical klines are fetched until Binance API returns no results. With every query start_ts is incremented. For the most part this cause one unnecessary query to Binance to be made, where start_ts is bigger than end_ts. Moreover, when fetching klines for future markets (not spot), Binance API returns an error in such condition (-1023). This makes it impossible to fetch klines for future markets when providing end_str param.
=> Fix passing start_ts > end_ts when fetching historical klines

binance/streams.py, binance/threaded_stream.py
Fix #1200 and #1174 with Python 3.8.13
The stream does not work anymore with the standard code presented. We have to change the threading approach to run it successfully. Additionally, we should also be able to use the testnet for the futures stream in combination with the threaded approach, so that has also been fixed. @sammchardy 
Minimal testing example:
```python
import time
from binance.streams import ThreadedWebsocketManager
def handler(order_data):
print(order_data)
manager = ThreadedWebsocketManager(
API_KEY, 
API_SECRET, 
testnet=True
)
manager.daemon = True # ctrl-c works
manager.start()
manager.start_futures_user_socket(handler)
while True:
time.sleep(0.1)
```
=> Fixed threaded stream and futures user socket

docs/market_data.rst
lines 88 for kline in client.get_historical_klines_generator("BNBBTC", Client.KLINE_INTERVAL_1MINUTE, "1 day ago UTC") need a ':' at the end;
=> Correction of sample program syntax issues

binance/exceptions.py
When Binance API is sending an unexpected response text, it sometimes doesn't have "code" or "msg" fields in the response and thus the following exception occurs:
`File "/usr/local/lib/python3.8/dist-packages/binance/exceptions.py", line 14, in __init__ self.code = json_res['code'] KeyError: 'code'`
This patch is to add a default handling when key is not present in JSON response.
=> Add default handling when key is not in json response

binance/client.py
In my case, I needed a `trace_configs` from `aiohttp.ClientSession` params. May be useful.
=> add params for AsyncClient

binance/client.py
The URL of the options is not correct.
----------------------
The base endpoint is: **https://eapi.binance.com
GET /eapi/v1/ping
https://binance-docs.github.io/apidocs/voptions/en/#general-api-information
=> modify options url

binance/streams.py, test-requirements.txt, tests/test_streams.py
`_exit_coro` is passed the wrong argument in `__aexit__`, so the object is not being removed from the `_conn` dictionary in the `BinanceSocketManager`.
=> fix bad argument to exit_core in ReconnectingWebsocket

binance/client.py
The `name` parameter is no longer mandatory according to Binance docs (https://developers.binance.com/docs/binance-trading-api/spot#withdrawuser_data) and my test.
It may only do harm if it automatically saves the withdrawal address to the address book and bloats it (the limit is 500 items and then it starts rejecting withdrawals).
=> Dont force name param in withdraw

binance/client.py
The phrase comission in Client.futures_comission_rate seems like a typo. Changing it to "commission" makes more sense.
=> Fix method name typo in Client.futures_comission_rate

binance/client.py
endpoint changed for `get_products` from `exchange-api/v1/public/asset-service/product/get-products` (obsolete) to  `bapi/asset/v2/public/asset-service/product/get-products?includeEtf=true` (new)
=> Update endpoint for get_products

binance/threaded_stream.py
Fixed event loop creation issue in threaded_stream.py file by simple checking if the loop is already created or not. If is not created - create a new one, otherwise get current one
=> Fixed event loop creation issue in threaded_stream.py file

binance/client.py
Simple but missing function, to be able to modify an existing order.
For example it is usefull for modifing the quantity, or the price of an open order.
Using the same url (order) as for creating a new order but with a PUT method instead of a POST method.
=> Add - futures_modify_order function

binance/client.py
Added get_spot_delist_schedule for [Get symbols delist schedule for spot](https://binance-docs.github.io/apidocs/spot/en/#get-symbols-delist-schedule-for-spot-market_data).
Added get_margin_delist_schedule for [Get tokens or symbols delist schedule for cross margin and isolated margin](https://binance-docs.github.io/apidocs/spot/en/#get-tokens-or-symbols-delist-schedule-for-cross-margin-and-isolated-margin-market_data).
=> Added delist schedules for spot and margin market data

binance/client.py
Added CountdownCancelAll to [Auto-Cancel All Open Orders](https://binance-docs.github.io/apidocs/futures/en/#auto-cancel-all-open-orders-trade)
=> Added CountdownCancelAll to Auto-Cancel All Open Orders

binance/client.py
Docstring in function futures_api_trading_status is wrong (it was referring to adlQuantile information, which is related to a different endpoint.
=> Update client.py to fix docstring

binance/depthcache.py
Current implementation of refresh interval doesn't work correct according to the library documentation -- setting the `refresh_interval` argument to 0 or None will actually set it to default value (30 minutes).
My fix doesn't change the behavior as advertised, it will set `refresh_interval` to default when not specified, and disabled when 0 or None is passed.
=> Allow to actually disable refresh interval

Endpoints.md, binance/client.py
Adding long awaited endpoint that I requested some time ago. https://www.binance.com/en-GB/my/user-support/feedback/detail/29679?feedbackIndex=0
`POST /sapi/v1/margin/manual-liquidation` [see docs](https://binance-docs.github.io/apidocs/spot/en/#margin-manual-liquidation-margin)
=> Add manual liquidation endpoint

binance/client.py
I'm not exactly sure how async functions suppose to work as I haven't used them yet, I simply followed the pattern how the other functions are written. So, I'm not sure if async functions are working, otherwise, it's tested, and written with documentation. 
P.S. 
Cards on the table, I'm having difficulty understanding in what hierarchy I should write the code, at this point I randomly select a line and add functions there. So let me know if you have a guideline for that.
=> Added the absent api call functions in "Margin Account/Trade" section

binance/__init__.py, binance/streams.py
- relates to https://github.com/sammchardy/python-binance/issues/1455
=> feat(client): add futures_ticker_socket and futures_coin_ticker_socket

binance/async_client.py, binance/client.py
Note: Did not have the keys to live test.
=> feat: add support for block trades endpoints

binance/async_client.py, binance/client.py, tests/test_async_client_futures.py, tests/test_client_futures.py
Note: tested with mock unit tests, but not with live keys
=> feat: add async dapi endpoints

examples/create_oco_order.py
- fixes https://github.com/sammchardy/python-binance/issues/1495
=> examples: add oco_order example

binance/async_client.py, binance/client.py, binance/enums.py, tests/test_async_client.py, tests/test_async_client_futures.py, tests/test_client_futures.py
Thank you for the excellent library!  
I noticed that the endpoint for **Mark Price Kline/Candlestick Data** is missing.  
You can refer to this link for more details: [Mark Price Kline/Candlestick Data](https://binance-docs.github.io/apidocs/futures/en/#mark-price-kline-candlestick-data)
=> feat(client): add futures_mark_price_klines, futures_index_price_klines, futures_premium_index_klines

docs/binance.rst, docs/conf.py, docs/requirements.txt
Fixes docs to include full API reference
Can test locally by: 
```
cd docs
pip install -r requirements.txt
python -m sphinx -T -b html -d _build/doctrees -D language=en . output/html
cd output/html
python -m http.server
```
=> feat: fix docs to show all docstrings

.readthedocs.yaml, docs/requirements.txt
**Issue**: Currently docs not generating completly.
**Why**: "sphinx.ext.autodoc" plugin requires to install all dependencies of the project
**Solution**: Have read-the-docs install also project requirements during build
An alternative is to mock all the requirements in the conf.py file, but this would require making sure it is changed anytime requirements.txt is changed.
=> fix: docs requirements

binance/__init__.py, binance/async_client.py, binance/base_client.py, binance/client.py, binance/ws/keepalive_websocket.py, binance/ws/streams.py, tests/test_async_client.py, tests/test_client.py, tests/test_client_ws_api.py, tests/test_streams.py
Allows to set Time_unit to receive timestamps in microseconds.
Binance instroduced feature 2024-12-17
https://developers.binance.com/docs/binance-spot-api-docs#2024-12-17
=> feat:add support for microseconds time unit

binance/async_client.py, binance/client.py
Note: not tested with live keys - but matches request
=> feat: add futures data link

binance/ws/reconnecting_websocket.py
When closing the BinanceWebsocket in some cases the websocket will close before the readloop, causing the read loop to return to the user a ClosedConnectionError.
- When closing the binanceWebsocket, first the read loop is exited and the websocket is stopped.
- Remove unnecesary line of setting the ws state to Exiting as it's done already inside `_kill_read_loop`
=> fix: close read loop before closing websocket fix #1530

Endpoints.md, binance/async_client.py, binance/client.py, tests/test_async_client_futures.py, tests/test_client_futures.py
I saw some APIs are implemented but their statuses are not updated in Endpoints.md. It may be intended to be like that, so correct me if I'm wrong.
I also add `client.futures_taker_longshort_ratio` using **takerlongshortRatio** endpoint from finance.
Finally, I update the tests for all of the above APIs
=> Update Endpoints.md, add futures_taker_longshort_ratio and update tests

binance/async_client.py, binance/client.py, binance/ws/keepalive_websocket.py, binance/ws/streams.py
Note: did not have api key to test
=> feat: portfolio margin user data streams

binance/client.py
=> chore: update docs for create_oco_order

.github/workflows/python-app.yml
We had some actions run for 360 minutes due to proxy not working. This adds a timeout to github action
=> add timeout to github actions

binance/ws/reconnecting_websocket.py, test-requirements.txt, tests/test_async_client_ws_futures_requests.py
=> fix: json_dumps when using orjson

.github/workflows/python-app.yml, binance/ws/websocket_api.py, tests/test_ws_api.py
**Problem**: Ws api wasn't allowing to send over 100 requests, as they were being stored in `_queue` and user was not calling _recv(). This was causing the queue to hit the MAX_SIZE
**Solution**: For those messages part of the ws_api there are not put into the recv queue as they are already stored in `_responses` and returned to the user in the future when making the ws_api_request
Note: This would stop any user using `recv()` from receiving `ws_api_request` messages through there. But as the docs don't specify it, and users already receive the message through the future returned by the ws_api_request, I believe this is a safe change.
Fixes #1559
=> fix: ws api not allowing to send over 100 requests

binance/async_client.py, binance/client.py
- Some endpoints return a status.code 200 with an empty response. Here the library was throwing a ValueError.
- Fixes pyright error for get_all_tickers
Return an empty json in case of an empty response
=> fix: return empty json instead of throwing error on empty response

.github/workflows/python-app.yml, binance/async_client.py, tests/test_async_client.py, tests/test_client.py
- **add timeout to jobs**
- **fix: fix response for async client when receiving empty text response**
=> fix: async client receive empty text

.github/workflows/python-app.yml, binance/async_client.py, binance/ws/reconnecting_websocket.py, binance/ws/streams.py, binance/ws/threaded_stream.py, pyproject.toml, test-requirements.txt, tests/test_reconnecting_websocket.py, tests/test_streams_options.py, tests/test_threaded_socket_manager.py, tests/test_threaded_stream.py, tests/test_ws_api.py, tox.ini
- Move MAX_QUEUE_SIZE from constant to variable set by user on starting ThreadedWebsocket or BinanceWebsocket
- Have async callbacks run in a task to better performance of slow async callbacks. (Before one had to finish before calling the next one)
- Fix passing keys and proxy to threaded socket manager
- Adds pytest-timeout and timeout of 60seconds for tests
- Add tests
- Update docs
- Increase verbosity in test running
- Comments coveralls: (Temporarily due to due to coveralls maintenance of April 6 2025: https://status.coveralls.io/)
=> feat: Expose option for user to edit max_queue_size in websockets, have async callbacks called in a task and update docs

binance/helpers.py
datetime.datetime.utcfromtimestamp() will be deprecated in future versions
=> fixed a deprecation warning in helpers.py

.github/workflows/python-app.yml, binance/ws/depthcache.py, binance/ws/reconnecting_websocket.py, binance/ws/threaded_stream.py, docs/depth_cache.rst, examples/depth_cache_example.py, examples/depth_cache_threaded_example.py
- Currently the depth manager if the underlying socket closes, does not notify the user
- No error was returned on a cancelled loop
- Improves error handling for depth manager and threaded manager.
- Notifies user in the case of a disconnect and allows the user to ignore so websocket automatically reconnects
- Improved logging
- Add docs for error handling
- Added examples for both depth manager and  threaded depth manager
Note for backward compatibility: Previous users were told to expect to recieve a None in case of an error and now we are returning a message containing an error
=> Improve error handling for depth manager

.github/workflows/python-app.yml, binance/base_client.py, binance/helpers.py, binance/ws/streams.py, tests/conftest.py, tests/test_async_client.py, tests/test_async_client_futures.py, tests/test_async_client_margin.py, tests/test_async_client_options.py, tests/test_async_client_ws_api.py, tests/test_async_client_ws_futures_requests.py, tests/test_client_futures.py, tests/test_client_ws_futures_requests.py, tests/test_threaded_stream.py
Testnet urls stoped working, updateing to latest values.
Reference:
https://developers.binance.com/docs/binance-spot-api-docs/testnet#general-changes
=> chore: update testnet urls
